# this should follow the Go reference time format
# see <https://go.dev/src/time/format.go> for more information
dateformat = "2006/01/02"

# this value should be a float between 0 and 1, this tracks how much
# of the screen should be scrolled when the article is marked as read
read_threshold = 0.8

# these values can be any format that lipgloss supports
# see <https://github.com/charmbracelet/lipgloss#colors>
[colors]
text = "#cdd6f4"
inverttext = "#1e1e2e"
subtext = "#a6adc8"
accent = "#74c7ec"
borders = "#313244"
