# this should follow the Go reference time format
# see <https://go.dev/src/time/format.go> for more information
dateformat = "2006/01/02"

# these values can be any format that lipgloss supports
# see <https://github.com/charmbracelet/lipgloss#colors>
[colors]
text = "#cdd6f4"
inverttext = "#1e1e2e"
subtext = "#a6adc8"
accent = "#74c7ec"
borders = "#313244"
