# all examples in this file differ from the default settings
# to show how this file may be changed for a better user experince

# this should follow the Go reference time format
# see <https://go.dev/src/time/format.go> for more information
dateformat = "2006/01/02"

# a list of urls to fetch rss feeds from
urls = [
  "https://isabelroses.com/feed.xml",
  "https://robinroses.xyz/feed.xml",
]

# there are settings that only apply to the reader view
[reader]
# this value should be a float between 0 and 1, this tracks how much
# of the screen should be scrolled when the article is marked as read
read_threshold = 0.75

# this value can be "most", "recommended" or "full" and controls the
# width of the article should be displayed to the users screen
# this value can also be an int, however this is not recommended as
# it will not be responsive to screen sizes
size = "full"

# this value can be "environment" or a path to a glamour file otherwise this
# will default auto style based on the terminal
theme = "environment"

# these values can be any format that lipgloss supports
# see <https://github.com/charmbracelet/lipgloss#colors>
[colors]
text = "#D6CBB4"
inverttext = "#252B2E"
subtext = "#6E8585"
accent = "#B2C98F"
borders = "#46545B"
